version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
          name: Install dependencies
      - run:
          command: pytest tests/unit/
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
